<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

$currentDate       = JFactory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = $this->item->publish_down < $currentDate && $this->item->publish_down !== JFactory::getDbo()->getNullDate();

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative) { echo $this->item->pagination; } ?>

	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date') || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print"><?php echo JHtml::_('icon.print_screen', $this->item, $params); ?></div>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position))) || (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>

    <?php echo JLayoutHelper::render('joomla.content.pa_weblog_article_full_image', $this->item); ?>

    <div class="uk-container uk-container-small uk-position-relative">
        <div class="uk-padding uk-box-shadow-small uk-border-rounded uk-card uk-card-default">
            <div>
                <?php if ($params->get('access-view')) : ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	endif;
	?>
	<?php if (isset ($this->item->toc)) :
		echo $this->item->toc;
	endif; ?>

        <?php if ($params->get('show_title')) : ?>
            <div class="page-header uk-margin-small-bottom">
                <h2 itemprop="headline" class="uk-text-bold uk-text-center font uk-text-dark uk-margin-remove"><?php echo $this->escape($this->item->title); ?></h2>
                <?php if ($this->item->state == 0) : ?>
                    <span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
                <?php endif; ?>
                <?php if ($isNotPublishedYet) : ?>
                    <span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
                <?php endif; ?>
                <?php if ($isExpired) : ?>
                    <span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php if (!$this->print) : ?>
            <?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
                <?php // echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
            <?php endif; ?>
        <?php else : ?>
            <?php if ($useDefList) : ?>
                <div id="pop-print" class="btn hidden-print">
                    <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
        <?php // echo $this->item->event->afterDisplayTitle; ?>

        <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
            <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
                    <div class="uk-flex uk-flex-center uk-margin-bottom"><?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?></div>
        <?php endif; ?>

	<div itemprop="articleBody" class="uk-text-justify uk-text-dark font"><?php echo $this->item->fulltext; ?></div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = JFactory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="register">
			<?php if ($params->get('alternative_readmore', '') === '') : ?>
				<?php echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE'); ?>
			<?php else : ?>
				<?php echo $params->get('alternative_readmore'); ?>
				<?php if ($params->get('show_readmore_title', 0) != 0) : ?>
					<?php echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit')); ?>
				<?php endif; ?>
			<?php endif; ?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>
                <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                    <?php $this->item->tagLayout = new JLayoutFile('joomla.content.pa_article_tags'); ?>

                    <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
                <?php endif; ?>

                <hr class="uk-margin-medium">
                <div class="uk-grid-small" data-uk-grid>
                    <div class="uk-width-auto uk-flex uk-flex-middle uk-visible@m">
                        <span class="uk-text-dark uk-text-small font"><?php echo JText::sprintf('SHARETHIS'); ?></span>
                    </div>
                    <div class="uk-width-1-1 uk-width-expand@m">
                        <ul class="uk-grid-small uk-child-width-1-4 uk-child-width-auto@m" data-uk-grid>
                            <li><a href="https://www.facebook.com/sharer.php?u=<?php echo JURI::current(); ?>" target="_blank" class="uk-width-1-1 uk-button uk-border-rounded uk-text-zero uk-padding-remove-horizontal uk-button-facebook"><img class="uk-margin-small-left uk-margin-small-right" src="<?php echo JURI::base().'images/sprite.svg#facebook'; ?>" width="16" height="16" data-uk-svg></a></li>
                            <li><a href="https://twitter.com/share?url=<?php echo JURI::current(); ?>&text=<?php echo $this->escape($this->item->title); ?>" target="_blank" class="uk-width-1-1 uk-button uk-border-rounded uk-text-zero uk-padding-remove-horizontal uk-button-twitter"><img class="uk-margin-small-left uk-margin-small-right" src="<?php echo JURI::base().'images/sprite.svg#twitter'; ?>" width="16" height="16" data-uk-svg></a></li>
                            <li><a href="tg://msg_url?url=<?php echo JURI::current(); ?>&text=<?php echo $this->escape($this->item->title); ?>" target="_blank" class="uk-width-1-1 uk-button uk-border-rounded uk-text-zero uk-padding-remove-horizontal uk-button-telegram"><img class="uk-margin-small-left uk-margin-small-right" src="<?php echo JURI::base().'images/sprite.svg#telegram'; ?>" width="16" height="16" data-uk-svg></a></li>
                            <li><a href="https://wa.me/?text=<?php echo JURI::current(); ?>" target="_blank" class="uk-width-1-1 uk-button uk-border-rounded uk-text-zero uk-padding-remove-horizontal uk-button-whatsapp"><img class="uk-margin-small-left uk-margin-small-right" src="<?php echo JURI::base().'images/sprite.svg#whatsapp'; ?>" width="16" height="16" data-uk-svg></a></li>
                        </ul>
                    </div>
                    <div class="uk-width-1-1 uk-width-auto@m">
                        <a href="<?php echo JRoute::_(ContentHelperRoute::getCategoryRoute($this->item->catslug)); ?>" class="uk-button uk-button-default uk-border-rounded uk-box-shadow-small uk-width-1-1 font"><?php echo JText::sprintf('BACKTO').' '.$this->item->category_title; ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>


<section class="uk-margin-large-top uk-margin-bottom">
    <div>
        <div class="uk-container">
            <div class="title uk-margin-bottom">
                <h3 class="uk-margin-remove uk-text-center uk-text-bold uk-text-secondary font"><?php echo JTEXT::_('OTHERBLOGITEMS'); ?></h3>
            </div>
            <div data-uk-slider>
                <div class="uk-position-relative">
                    <div class="uk-slider-container uk-padding-small uk-padding-remove-top">
                        <div class="uk-child-width-1-1 uk-child-width-1-3@m uk-slider-items" data-uk-grid>
                            <?php
                            $db = JFactory::getDbo();
                            $otherItems = $db->getQuery(true);
                            $otherItems
                                ->select($db->quoteName(array('id', 'catid')))
                                ->from($db->quoteName('#__content'))
                                ->where($db->quoteName('catid') . ' = ' . $this->item->catid)
                                ->where($db->quoteName('state') . ' = ' . 1)
                                ->where($db->quoteName('id') . ' != ' . $this->item->id)
                                ->order('rand()');
                            $items = $db->setQuery($otherItems, 0, 9)->loadColumn();
                            ?>
                            <?php for ($k=0;$k<count($items);$k++) { $article = JTable::getInstance('content'); $article->load($items[$k]); ?>
                                <div class="uk-height-1-1">
                                    <div class="uk-card uk-card-default uk-border-rounded uk-box-shadow-small uk-overflow-hidden uk-height-1-1">
                                        <div class="uk-card-media-top pull-left item-image">
                                            <a class="uk-display-block uk-cover-container blogImagePlaceholder" href="<?php $relatedItemsSlug = $article->get('id').':'.$article->get('alias'); echo ContentHelperRoute::getArticleRoute($relatedItemsSlug, $article->get('catid'), $article->get('language')); ?>" title="<?php echo $article->get('title'); ?>">
                                                <canvas width="400" height="225"></canvas>
                                                <?php if (!empty(json_decode($article->get('images'))->image_intro)) { ?>
                                                    <img src="<?php echo json_decode($article->get('images'))->image_intro; ?>" alt="<?php echo $article->get('title'); ?>" itemprop="thumbnailUrl" data-uk-cover>
                                                <?php } else { ?>
                                                    <div class="uk-background-muted" data-uk-cover></div>
                                                    <img src="<?php echo JURI::base().'images/sprite.svg#logo'; ?>" alt="<?php echo $article->get('title'); ?>" width="80" height="80" itemprop="thumbnailUrl" class="uk-position-center" data-uk-svg>
                                                <?php } ?>
                                            </a>
                                        </div>
                                        <div class="uk-card-body uk-padding-small">
                                            <div class="uk-padding-small">
                                                <div>
                                                    <dl class="article-info muted uk-margin-small-bottom uk-grid-small uk-grid-divider uk-text-tiny" data-uk-grid>
                                                        <dd class="published">
                                                            <time class="font uk-text-muted" datetime="<?php echo $article->get('publish_up'); ?>" itemprop="datePublished"><?php echo JText::sprintf('COM_CONTENT_PUBLISHED_DATE_ON', JHtml::date($article->get('publish_up'), 'd F Y')); ?></time>
                                                        </dd>
                                                        <dd class="hits">
                                                            <meta itemprop="interactionCount" content="UserPageVisits:<?php echo $article->get('hits'); ?>">
                                                            <span class="font uk-text-muted"><?php echo JText::sprintf('COM_CONTENT_ARTICLE_HITS', $article->get('hits')); ?></span>
                                                        </dd>
                                                    </dl>
                                                </div>
                                                <div class="page-header">
                                                    <h2 itemprop="name" class="uk-h4 uk-margin-remove uk-text-truncate">
                                                        <a class="font uk-text-bold uk-text-dark hoverSecondary" href="<?php $relatedItemsSlug = $article->get('id').':'.$article->get('alias'); echo ContentHelperRoute::getArticleRoute($relatedItemsSlug, $article->get('catid'), $article->get('language')); ?>" itemprop="url"><?php echo $article->get('title'); ?></a>
                                                    </h2>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin-top"></ul>
                </div>
            </div>
        </div>
    </div>
</section>